services:
    react-app-dockerize:
        container_name: fugrru_c

        image: fugrru_i

        build:
            context: .
            dockerfile: Dockerfile

        ports:
            - "5173:5173" 

        volumes:
            - .:/app
            - /app/node_modules

        command: npm run dev